// Code generated by "stringer -type=Actions -output stringer.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[North-0]
	_ = x[East-1]
	_ = x[South-2]
	_ = x[West-3]
	_ = x[ActionsN-4]
}

const _Actions_name = "NorthEastSouthWestActionsN"

var _Actions_index = [...]uint8{0, 5, 9, 14, 18, 26}

func (i Actions) String() string {
	if i < 0 || i >= Actions(len(_Actions_index)-1) {
		return "Actions(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Actions_name[_Actions_index[i]:_Actions_index[i+1]]
}
